### ISSUE TITLE
API Link returns 404

### ISSUE THREAD

**Issue by rschoolu** [Weilbyte/tiktok-tts#10]
The API Link returns a 404 error.

**Comment by Weilbyte** [comment]
Hi, I am aware

**Comment by rschoolu** [comment]
I don't think it's something in the code that's faulty. It's probably the API link itself.

**Comment by Weilbyte** [comment]
Yes, they have changed the API endpoint for TTS

**Comment by rschoolu** [comment]
How would this be fixed? Or is it unfixable?

**Comment by alexgarciab** [comment]
Following

**Comment by elidigital** [comment]
Is this fixable?

**Comment by rschoolu** [comment]
I don't know. Maybe if like a new link can be found or something? For the api cuz the api link returns a 404, meaning it doesn't exist anymore, maybe it got moved.

**Comment by ItsFreshify** [comment]
i believe if you sign up to become a tiktok devolper they give you the api info

**Comment by Weilbyte** [comment]
@ItsFreshify I looked around and it's a very limited subset of their API that they give you access to. It does not include the TTS engine.

**Comment by rschoolu** [comment]
so does this mean that tiktok tts rip?

**Comment by Weilbyte** [comment]
If I recall correctly, oscie57's python CLI tool.  Generally yes but I have not been successful in intercepting the HTTPS traffic from the app, because it crashes on every emulator I tried it on, now, the TikTok Lite app works but It doesn't seem to have TTS support so it's not making those requests anyway. 

And I don't have a rooted Android phone at hand. Even if I did I'm pretty sure if this was a deliberate action towards tools like this, that they would have also added authentication requirements to the endpoint.

**Comment by xfrcc** [comment]
I have a device with root, and properly hiding it from tiktok, but can't intercept the requests too, it does work triggerint the tts when editing a video tho

**Comment by Weilbyte** [comment]
@xfrcc which android version? iirc if above 6.0, you need to patch the APK to accept the MITM proxy's CA

**Comment by xfrcc** [comment]
> @xfrcc which android version? iirc if above 6.0, you need to patch the APK to accept the MITM proxy's CA

7.1.2, i've tried patching with apk-mitm, but not working because apktool it's parsing bad the xml's

**Comment by xfrcc** [comment]
Got news, new endpoint is `api22-normal-c-useast1a.tiktokv.com`, however, you must replicate now the headers like if it was in the app, i will test which one is necessary and which one us redundant

**Comment by Weilbyte** [comment]
Thank you!
I will attempt to reproduce and see how this can be implemented within this tool.

**Comment by rschoolu** [comment]
does this mean that the tts could work again?

**Comment by AdamAtomus** [comment]
> 

couldn't you use the session id from the web on pc?
![image](https://user-images.githubusercontent.com/42122290/188522649-083a3d29-0f3f-4dd5-b32c-d6edae14e2b2.png)

**Comment by AdamAtomus** [comment]
I get the Couldn't load speach, maybe it requires it to be a sessionid generated by logging in on phone? Not too sure, https://i.imgur.com/oPSNJiI.png

**Comment by Weilbyte** [comment]
A solution is in the works and expected to be out by Friday, if everything goes smoothly.

@AdamAtomus the `aid` parameter is wrong, it needs to be 1233

**Comment by AdamAtomus** [comment]
> A solution is in the works and expected to be out by Friday, if everything goes smoothly.
> 
> @AdamAtomus the `aid` parameter is wrong, it needs to be 1233

yeah same issue, what SID did you use? from the app or from website on pc

**Comment by Petter1515** [comment]
Thank you! @xfrcc  and @Weilbyte ! Cheers!
