### ISSUE TITLE
Larger text limit and Worker Source

### ISSUE THREAD

**Issue by iRajatDas** [Weilbyte/tiktok-tts#27]
Hi, I want to use these voices to create YouTube videos but it takes a lot of time to break the text into 300 chars and generate copy edit and all.

It would be nice if you could increase the text limit.

Also, please provide the worker's source if possible.

Thanks for this tool!

**Comment by Weilbyte** [comment]
Please note that the text limit cannot be increased as it is a limitation imposed by TikTok. You can however create a script that splits your text at 300 **bytes** (very important) and sends a generation API request (check F12 network tab on how to structure request) for each segment.

Project is pending a rewrite however, and this behavior will be integrated once that is done.
