### ISSUE TITLE
Error submitting form (printed to console).

### ISSUE THREAD

**Issue by Allofthem0001** [Weilbyte/tiktok-tts#3]
It says this when im trying to generate a voice:
![image](https://user-images.githubusercontent.com/110870990/183539223-b7aabc8a-9d60-4f92-a75b-c0abeaa38d32.png)

**Comment by Petter1515** [comment]
Yes, me too. The browser has a problem. 

![image](https://user-images.githubusercontent.com/109671200/183583828-e6b2580d-9155-40a1-9ebc-345752a8deb8.png)

**Comment by alexgarciab** [comment]
Not working here either. There is a problem with warp-co.rs SSL cert. It expired a few hours ago and the requests are not being sent correctly as the browser needs a valid SSL on that domain. Any alternatives to that CORS proxy? @Weilbyte

**Comment by Weilbyte** [comment]
@alexgarciab will find an alternative once I get back from work. There should be plenty.

**Comment by Weilbyte** [comment]
There appears to still be an error because of bad URI encoding. Will be fixed soon.

**Comment by Weilbyte** [comment]
Fixed as of a few hrs ago.
