### ISSUE TITLE
Request: Download mp3?

### ISSUE THREAD

**Issue by Mycah** [Weilbyte/tiktok-tts#4]
Any way to download an mp3 of generated audio?

**Comment by Weilbyte** [comment]
You should be able to get a download option by clicking on the mp3 player options.

![image](https://user-images.githubusercontent.com/43392677/184437460-989ccc8d-9003-43b2-bde9-1451ecc8588a.png)
![image](https://user-images.githubusercontent.com/43392677/184437551-67d60d48-b578-4d80-b759-537d60ca6218.png)

**Comment by Mycah** [comment]
What browser is that?  It's not available in firefox.

**Comment by Weilbyte** [comment]
How does it look like on Firefox?

**Comment by Mycah** [comment]
pretty bare bones.
![Screenshot 2022-08-14 094750](https://user-images.githubusercontent.com/1263581/184546795-e5f352c5-954a-4ac8-9b8f-a6ebffd06d29.png)

**Comment by PotcFdk** [comment]
@Mycah right click the player UI and pick the save audio option?

**Comment by Mycah** [comment]
Cool, that seems to be an option.  I had no idea!  Thanks!  Fun tool, too!
