### ISSUE TITLE
Error submitting form

### ISSUE THREAD

**Issue by MajdFiras** [Weilbyte/tiktok-tts#48]
hello , is this will be fixed soon ? 
![Capture](https://github.com/Weilbyte/tiktok-tts/assets/104529748/1d536c69-0d8f-46eb-a974-e4a97b6515d8)

**Comment by Weilbyte** [comment]
Where do you see this and what are you trying to generate?

**Comment by Weilbyte** [comment]
Where exactly do you see this? The script does not contain `sendToPython` so I am not quite sure what you are referring to.

**Comment by MajdFiras** [comment]
> Where exactly do you see this? The script does not contain `sendToPython` so I am not quite sure what you are referring to.

when i try to convert the text to voice this message shown to me in the console log 
![image](https://github.com/Weilbyte/tiktok-tts/assets/104529748/24f2eba8-04d5-40ba-a459-3bd853b6ff55)

and this shown in the html view 

![image](https://github.com/Weilbyte/tiktok-tts/assets/104529748/4af27172-0d53-4302-aaa1-bd0a26fbbf41)
