### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by vytskalt** [Weilbyte/tiktok-tts#50]
503 Service Temporarily Unavailable

**Comment by goforrony** [comment]
Yes. Experiencing the same. Is there any timeline for the maintenance?
Really love this service and the website. Appreciate any information. @Weilbyte

**Comment by Weilbyte** [comment]
Up now.

**Comment by goforrony** [comment]
Thank you king @Weilbyte 
If you don't mind me asking, what happened? Was it a server issue?

**Comment by vytskalt** [comment]
broke again, `Could not generate: Unknown error: Error sending API request`
