### ISSUE TITLE
Can t use tts

### ISSUE THREAD

**Issue by Lfkedyn77** [Weilbyte/tiktok-tts#6]
I try to make a tiktok video but i can t, the site isn t working

**Comment by Petter1515** [comment]
![image](https://user-images.githubusercontent.com/109671200/185913823-fbc92f43-6b90-47aa-852b-0ab8c985f877.png)

The site has an error @Weilbyte :(

**Comment by Weilbyte** [comment]
Will take a look soon

**Comment by Kabir-k** [comment]
Tiktok tts is not working

**Comment by Kabir-k** [comment]
![Screenshot_20220822-222739](https://user-images.githubusercontent.com/97743706/185977193-e3549520-26f0-440f-998e-60e6acf2c5ec.png)

**Comment by Weilbyte** [comment]
Duplicate of #10
